# This file was generated by GoReleaser. DO NOT EDIT.
cask "zencoder" do
  name "zencoder"
  desc "AI coding assistant — local-first, multi-provider, auto-routing"
  homepage "https://github.com/divyabairavarasu/zencoder"
  version "4.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zencoder"
  binary "zencoderd"
  binary "zencoder-secrets"

  on_macos do
    on_intel do
      url "https://github.com/divyabairavarasu/zencoder/releases/download/v#{version}/zencoder_#{version}_darwin_amd64.tar.gz"
      sha256 "7a3c241c2873159c47c61b52b6cf949e5220a79e7f24c03333b49d8eb0465831"
    end
    on_arm do
      url "https://github.com/divyabairavarasu/zencoder/releases/download/v#{version}/zencoder_#{version}_darwin_arm64.tar.gz"
      sha256 "10223335291d167d605c275906ec552ee88445249113e215b5506fb7a082930a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/divyabairavarasu/zencoder/releases/download/v#{version}/zencoder_#{version}_linux_amd64.tar.gz"
      sha256 "62df3a3ef3f626f2c7c73bcb3498dfdfce60b577a44ae11e1e96a751da93875d"
    end
    on_arm do
      url "https://github.com/divyabairavarasu/zencoder/releases/download/v#{version}/zencoder_#{version}_linux_arm64.tar.gz"
      sha256 "f53ce32c7bf95a424ace24e8a7337d8c81473180117106f5a5377a196f60aa0d"
    end
  end

  # No zap stanza required
end
